apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-docker-app-deployment
  labels:
    app: hello-docker-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-docker-app
  
  template:
    metadata:
      labels:
        app: hello-docker-app
    
    spec:
      containers:
      - name: hello-docker-app
  
        image: kuigan/hello-docker-app
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
