apiVersion: v1
kind: Pod
metadata:
  name: hello-docker-app
  labels:
    name: hello-docker-app
    app: hello-docker-app
    environment: test
spec:
  containers:
  - name: hello-docker-app
    image: kuigan/hello-docker-app
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000
